---
title:               Maximum President
tagline:             Technology, Economics, Anarchomancy
login:               <%= ENV["obtvse_login"] ? ENV["obtvse_login"] : "garbados" %>
password:            <%= ENV["obtvse_password"] ? ENV["obtvse_password"] : "bienvenue4obtvse!" %>
name:                Max Thayer
twitter:             garbados
github:              garbados
email:               garbados@gmail.com
google_analytics_id: YOUR_GA_ID
